export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
// Analytics Actions
export const GET_ANALYTICS_OPEN_TICKETS = "GET_ANALYTICS_OPEN_TICKETS";
export const GET_ANALYTICS_AVG_RESOLVE = "GET_ANALYTICS_AVG_RESOLVE";
export const GET_ANALYTICS_TEAM_HISTORY = "GET_ANALYTICS_TEAM_HISTORY";
export const LOADING_DATA = "LOADING_DATA";

// Dashboard Actions
export const GET_TICKETS_OVERVIEW = "GET_TICKETS_OVERVIEW";
export const GET_TICKET_DETAILS = "GET_TICKETS_DETAILS";
export const TICKET_OVERVIEW_LOADING = "TICKET_OVERVIEW_LOADING";
export const TICKET_DETAILS_LOADING = "TICKET_DETAILS_LOADING";
export const CLEAR_TICKETS = "CLEAR_TICKETS";
export const CLEAR_DETAILS = "CLEAR_DETAILS";
