export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ANALYTICS_OPEN_TICKETS = "GET_ANALYTICS_OPEN_TICKETS";
export const GET_ANALYTICS_AVG_RESOLVE = "GET_ANALYTICS_AVG_RESOLVE";
export const GET_ANALYTICS_TEAM_HISTORY = "GET_ANALYTICS_TEAM_HISTORY";