export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// Dashboard Actions
export const GET_TICKETS_OVERVIEW = "GET_TICKETS_OVERVIEW";
export const GET_TICKET_DETAILS = "GET_TICKETS_DETAILS";
export const TICKET_OVERVIEW_LOADING = "TICKET_OVERVIEW_LOADING";
export const TICKET_DETAILS_LOADING = "TICKET_DETAILS_LOADING";